Add parens after lambda substitution during Span.update
EasyArray/phosphorus pull request #33
Opened 2022-03-09 19:37 UTC by havijw

This should resolve #32. Added a function to check whether a string is wrapped it parentheses. Then, during `Span.update`, use this after a &beta;-reduction to check whether the result needs to be wrapped in parens; if so, add the parens.

This results in extra parens when the result is already wrapped in parens, so for example

```py
```

2022-03-10 01:37 UTC, havijw commented
Update: fixed the issue with adding extra parenthesis when there are already surrounding delimiters!

2022-03-10 21:28 UTC, EasyArray requested changes
- This relies on the fact that LambdaVal.sub always return a string, so I'll have to remember that in case something changes. (hasdelimiters works on strings) Could you add a comment?
- Can you check if the function call is the only thing in the span being updated (`self`)? We don't need parens then. Currently `[λf . [λn . f(n)]]([λn .n+7])` comes out as `[λn∈e.(n+7)]` .

2022-03-11 03:12 UTC, havijw commented
Taking care of these now. One thought on the first bullet point:
- I could alternatively just convert to a string before calling `hasdelimiters` in `update`, or add a check in `hasdelimiters` to convert non-string input to a string. I'm inclined toward the latter option, but any of the others would also work.

2022-03-11 14:19 UTC, EasyArray commented
Am I correct that `singleItem` will be True every time that `hasdelimiters` returns true? Actually, since it's a string, `singleItem` will really only be true for a single character, right? Maybe some of these checks should happen after converting to a Span? Then `singleItem` will be true for *any* single item, including a Span with its own delimiters, I think. Worth checking though.

2022-03-11 21:17 UTC, havijw commented
I think you're right that the logic can be simplified here. In both cases, `singleItem` checks whether a `Span` has length 1, either because `item` is already a `Span` or because `item` is parsed as a `Span` before calling length. So I agree that `hasdelimiters` is redundant now, since any time `item` has delimiters around it, the `Span` it creates will have length 1.

2022-03-13 16:15 UTC, EasyArray commented on phosphorus/parse.py
>                      if item.printlen() == 1: item = item[0]
I believe that this line removes parentheses from single-item Spans -- maybe worth testing how it interacts with the logic above?

2022-03-13 16:18 UTC, EasyArray approved these changes

2022-03-13 16:29 UTC, merged